image: flemay/musketeers

# overlay2 provides improved performance for dind
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - test
  - build
  - deploy_dev
  - deploy_qa
  - deploy_prod

test:
  stage: test
  script:
    - make test

build:
  stage: build
  artifacts:
    paths:
      - bin
    expire_in: 1 month
  only:
    - master
  script:
    - make build pack

deploy_dev:
  stage: deploy_dev
  dependencies:
    - build
  script:
    - make deploy
  environment:
    name: DEV
  only:
    - master
  variables:
    ENV: dev
    ECHO_MESSAGE: dev-musketeers-lambda-go-serverless
    AWS_REGION: ap-southeast-2

deploy_qa:
  stage: deploy_qa
  dependencies:
    - build
  script:
    - make deploy
  environment:
    name: QA
  only:
    - master
  variables:
    ENV: qa
    ECHO_MESSAGE: qa-musketeers-lambda-go-sls
    AWS_REGION: ap-southeast-2

deploy_prod:
  stage: deploy_prod
  when: manual
  dependencies:
    - build
  script:
    - make deploy
  environment:
    name: PROD
  only:
    - master
  variables:
    ENV: prod
    ECHO_MESSAGE: prod-musketeers-lambda-go-sls
    AWS_REGION: ap-southeast-2
