image: flemay/musketeers

# overlay2 provides improved performance for dind
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - deps
  - test
  - build
  - deploy_dev
  - deploy_qa
  - deploy_prod

deps:
  stage: deps
  cache:
    # Cache dependencies
    key: ${CI_JOB_NAME}
    paths:
      - vendor
  artifacts:
    paths:
      - vendor
    expire_in: 1 week
  script:
    - make deps

test:
  stage: test
  dependencies:
    - deps
  script:
    - make test

build:
  stage: build
  dependencies:
    - deps
  artifacts:
    paths:
      - bin
    expire_in: 1 month
  only:
    - master
  script:
    - make build pack

deploy_dev:
  stage: deploy_dev
  dependencies:
    - build
  script:
    - make deploy
  environment:
    name: DEV
  only:
    - master
  variables:
    ENV: dev

deploy_qa:
  stage: deploy_qa
  dependencies:
    - build
  script:
    - make deploy
  environment:
    name: QA
  only:
    - master
  variables:
    ENV: qa

deploy_prod:
  stage: deploy_prod
  when: manual
  dependencies:
    - build
  script:
    - make deploy
  environment:
    name: PROD
  only:
    - master
  variables:
    ENV: prod