sudo: required

services:
  - docker

jobs:
  include:
    - stage: test
      script: make test
    - stage: build
      script: make build
    - stage: deploy dev
      if: branch = master
      env:
        - ENV=dev
        - ECHO_MESSAGE=dev-musketeers-lambda-go-serverless
        - AWS_REGION=ap-southeast-2        
      script: make deploy
    - stage: deploy qa
      if: branch = master
      env:
        - ENV=qa
        - ECHO_MESSAGE=dev-musketeers-lambda-go-serverless
        - AWS_REGION=ap-southeast-2        
      script: make deploy