language: minimal

sudo: required

services:
  - docker

jobs:
  include:
    - stage: Test
      script: make test
    - stage: Build
      script: make build pack
    - stage: Deploy Dev
      deploy:
        provider: script
        script: make deploy
        skip_cleanup: true
        env:
          - ENV=travis-dev
          - ECHO_MESSAGE=dev-musketeers-lambda-go-serverless
          - AWS_REGION=ap-southeast-2
    - stage: Deploy QA
      deploy:
        provider: script
        script: make deploy
        on:
          branch: master
        skip_cleanup: true
        env:
          - ENV=travis-qa
          - ECHO_MESSAGE=qa-musketeers-lambda-go-serverless
          - AWS_REGION=ap-southeast-2  
      # ideally you would store the artifact from `build/pack`
      # and then deploy the same artifact to different environments
