version: '3.4'
services:
  golang:
    image: lambci/lambda:build-go1.x
    env_file: .env
    volumes:
      - .:/go/src/gitlab.com/flemay/musketeers-lambda-go-sls
    working_dir: /go/src/gitlab.com/flemay/musketeers-lambda-go-sls

  serverless:
    image: amaysim/serverless:1.49.1
    env_file: .env
    volumes:
      - $HOME/.aws:/root/.aws
      - .:/opt/app
    working_dir: /opt/app

  gauth:
    image: contino/aws-google-auth:0.0.28
    env_file: .env
    volumes:
      - ~/.aws:/root/.aws