version: '3.4'
services:
  golang:
    image: golang:1.12
    env_file: .env
    volumes:
      - .:/opt/app
    working_dir: /opt/app

  serverless:
    image: amaysim/serverless:1.49.0
    env_file: .env
    volumes:
      - $HOME/.aws:/root/.aws
      - .:/opt/app
    working_dir: /opt/app

  gauth:
    image: contino/aws-google-auth:0.0.28
    env_file: .env
    volumes:
      - ~/.aws:/root/.aws